apiVersion: v1
kind: Service
metadata:
  name: sage-api
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sage-api
